# Generated by Django 4.2.1 on 2023-05-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=50)),
                ('autore', models.CharField(max_length=30)),
                ('categoria', models.CharField(max_length=30)),
                ('nPagina', models.IntegerField()),
            ],
        ),
    ]
