# Generated by Django 4.2.1 on 2023-06-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_libro_ncopie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestiti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUtente', models.IntegerField()),
                ('libro', models.CharField(max_length=50)),
                ('nCopiePrestate', models.IntegerField()),
                ('dataRitiro', models.CharField(max_length=10)),
                ('dataConsegna', models.CharField(max_length=10)),
            ],
        ),
    ]
