# Generated by Django 4.2.1 on 2023-06-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_prestiti'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='nCopie',
            new_name='nCopieMax',
        ),
        migrations.AddField(
            model_name='libro',
            name='nCopieRitirate',
            field=models.IntegerField(null=True),
        ),
    ]
