# Generated by Django 4.2.1 on 2023-06-05 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_rename_ncopie_libro_ncopiemax_libro_ncopieritirate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prestiti',
        ),
    ]
